version: '3'
services:
  server:
    container_name: skeleton_server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    ports:
      - '${PORT}:${PORT}'
    command: npm run watch-server
